# Generated by Django 3.1 on 2020-10-26 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2200), django.core.validators.MinValueValidator(1768)])),
                ('gearbox', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], default=1)),
                ('color', models.CharField(blank=True, default='#0000ff', max_length=7, verbose_name='цвет')),
            ],
        ),
    ]
